import {
  type Address,
  type Transaction,
  type MpcSession,
  type AuditLogEntry,
  NETWORK_FEE,
} from "@/types"

const now = new Date()
const h = (hours: number) => new Date(now.getTime() - hours * 3600000).toISOString()
const m = (minutes: number) => new Date(now.getTime() - minutes * 60000).toISOString()

export const SEED_ADDRESSES: Address[] = [
  {
    id: "addr-1",
    address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    name: "ООО Ромашка_основной",
    type: "MAIN",
    network: "BITCOIN",
    balance: 3.45000000,
    createdAt: h(720),
  },
  {
    id: "addr-2",
    address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    name: "ООО Ромашка_транзитный",
    type: "TRANSIT",
    network: "BITCOIN",
    balance: 0.50000000,
    createdAt: h(600),
  },
  {
    id: "addr-3",
    address: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    name: "ООО Ландыш_основной",
    type: "MAIN",
    network: "BITCOIN",
    balance: 1.20000000,
    createdAt: h(500),
  },
  {
    id: "addr-4",
    address: "1CounterpartyXXXXXXXXXXXXXXUWLpVr",
    name: "ООО Ландыш_транзитный",
    type: "TRANSIT",
    network: "BITCOIN",
    balance: 0.10000000,
    createdAt: h(400),
  },
  {
    id: "addr-5",
    address: "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    name: "ООО Василёк_основной",
    type: "MAIN",
    network: "BITCOIN",
    balance: 5.00000000,
    createdAt: h(300),
  },
  {
    id: "addr-6",
    address: "1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Zb1",
    name: "ООО Василёк_транзитный",
    type: "MAIN",
    network: "BITCOIN",
    balance: 0.75000000,
    createdAt: h(200),
  },
  {
    id: "addr-7",
    address: "1FfmbHfnpaZjKFvyi1okTjJJusN455paPH",
    name: "ООО Пион_транзитный",
    type: "TRANSIT",
    network: "BITCOIN",
    balance: 0.30000000,
    createdAt: h(150),
  },
  {
    id: "addr-8",
    address: "1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw",
    name: "ООО Пион_основной",
    type: "MAIN",
    network: "BITCOIN",
    balance: 2.10000000,
    createdAt: h(100),
  },
]

export const SEED_MPC_SESSIONS: MpcSession[] = [
  {
    id: "mpc-1",
    transactionId: "tx-3",
    deadline: new Date(now.getTime() + 4 * 60000).toISOString(),
    signersApproved: [],
    signersRejected: [],
    createdAt: m(1),
  },
  {
    id: "mpc-2",
    transactionId: "tx-4",
    deadline: new Date(now.getTime() + 3 * 60000).toISOString(),
    signersApproved: [],
    signersRejected: [],
    createdAt: m(2),
  },
  {
    id: "mpc-3",
    transactionId: "tx-5",
    deadline: new Date(now.getTime() + 2 * 60000).toISOString(),
    signersApproved: [],
    signersRejected: [],
    createdAt: m(3),
  },
  {
    id: "mpc-4",
    transactionId: "tx-6",
    deadline: new Date(now.getTime() + 1.5 * 60000).toISOString(),
    signersApproved: ["signer1"],
    signersRejected: [],
    createdAt: m(4),
  },
  {
    id: "mpc-5",
    transactionId: "tx-7",
    deadline: new Date(now.getTime() + 1 * 60000).toISOString(),
    signersApproved: ["signer2"],
    signersRejected: ["signer1"],
    createdAt: m(5),
  },
  {
    id: "mpc-6",
    transactionId: "tx-8",
    deadline: h(1),
    signersApproved: ["signer1", "signer2"],
    signersRejected: [],
    createdAt: h(2),
  },
  {
    id: "mpc-7",
    transactionId: "tx-9",
    deadline: h(2),
    signersApproved: ["signer1", "signer2"],
    signersRejected: ["signer3"],
    createdAt: h(3),
  },
  {
    id: "mpc-8",
    transactionId: "tx-10",
    deadline: h(3),
    signersApproved: ["signer1", "signer3"],
    signersRejected: [],
    createdAt: h(4),
  },
  {
    id: "mpc-9",
    transactionId: "tx-11",
    deadline: h(5),
    signersApproved: [],
    signersRejected: ["signer1", "signer2"],
    createdAt: h(6),
  },
  {
    id: "mpc-10",
    transactionId: "tx-12",
    deadline: h(1),
    signersApproved: ["signer1"],
    signersRejected: [],
    createdAt: h(6),
  },
]

export const SEED_TRANSACTIONS: Transaction[] = [
  // 2 DRAFT (outbound)
  {
    id: "tx-1",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-1",
    fromAddress: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    toAddress: "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
    amount: 0.15,
    fee: NETWORK_FEE,
    status: "DRAFT",
    txHash: null,
    comment: "Выплата партнёру",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: null,
    createdAt: h(48),
    updatedAt: h(48),
  },
  {
    id: "tx-2",
    type: "INTERNAL",
    fromAddressId: "addr-3",
    fromAddress: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    toAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    amount: 0.25,
    fee: NETWORK_FEE,
    status: "DRAFT",
    txHash: null,
    comment: "Перевод на транзитный",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: null,
    createdAt: h(36),
    updatedAt: h(36),
  },
  // 3 WAITING_MPC
  {
    id: "tx-3",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-1",
    fromAddress: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    toAddress: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    amount: 0.50,
    fee: NETWORK_FEE,
    status: "WAITING_MPC",
    txHash: null,
    comment: "Перевод контрагенту",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-1",
    createdAt: m(1),
    updatedAt: m(1),
  },
  {
    id: "tx-4",
    type: "INTERNAL",
    fromAddressId: "addr-5",
    fromAddress: "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    toAddress: "1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Zb1",
    amount: 1.00,
    fee: NETWORK_FEE,
    status: "WAITING_MPC",
    txHash: null,
    comment: "Пополнение операционного кошелька",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-2",
    createdAt: m(2),
    updatedAt: m(2),
  },
  {
    id: "tx-5",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-8",
    fromAddress: "1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw",
    toAddress: "3Kzh9qAqVWQhEsfQz7zEQL1EuSx5tyNLNS",
    amount: 0.30,
    fee: NETWORK_FEE,
    status: "WAITING_MPC",
    txHash: null,
    comment: "Вывод клиента",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-3",
    createdAt: m(3),
    updatedAt: m(3),
  },
  // 2 MPC_SIGNING
  {
    id: "tx-6",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-6",
    fromAddress: "1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Zb1",
    toAddress: "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
    amount: 0.20,
    fee: NETWORK_FEE,
    status: "MPC_SIGNING",
    txHash: null,
    comment: "Оплата услуг",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-4",
    createdAt: m(4),
    updatedAt: m(3),
  },
  {
    id: "tx-7",
    type: "INTERNAL",
    fromAddressId: "addr-2",
    fromAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    toAddress: "1FfmbHfnpaZjKFvyi1okTjJJusN455paPH",
    amount: 0.10,
    fee: NETWORK_FEE,
    status: "MPC_SIGNING",
    txHash: null,
    comment: "Консолидация средств",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-5",
    createdAt: m(5),
    updatedAt: m(4),
  },
  // 3 COMPLETED (outbound)
  {
    id: "tx-8",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-1",
    fromAddress: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    toAddress: "1PerfectHashXXXXXXXXXXXXXXXXXXaknBJ",
    amount: 0.75,
    fee: NETWORK_FEE,
    status: "COMPLETED",
    txHash: "a1b2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef",
    comment: "Выплата дивидендов",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-6",
    createdAt: h(2),
    updatedAt: h(1),
  },
  {
    id: "tx-9",
    type: "INTERNAL",
    fromAddressId: "addr-5",
    fromAddress: "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    toAddress: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    amount: 2.00,
    fee: NETWORK_FEE,
    status: "COMPLETED",
    txHash: "b2c3d4e5f6789012345678901bcdef1234567890abcdef1234567890abcdef12",
    comment: "Перевод из резерва",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-7",
    createdAt: h(3),
    updatedAt: h(2),
  },
  {
    id: "tx-10",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-8",
    fromAddress: "1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw",
    toAddress: "1Archive1n2C579dMsAu3iC6tWzuQJz8dN",
    amount: 0.50,
    fee: NETWORK_FEE,
    status: "COMPLETED",
    txHash: "c3d4e5f67890123456789012cdef1234567890abcdef1234567890abcdef1234",
    comment: "Архивный перевод",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-8",
    createdAt: h(4),
    updatedAt: h(3),
  },
  // 1 REJECTED
  {
    id: "tx-11",
    type: "EXTERNAL",
    direction: "OUTBOUND",
    fromAddressId: "addr-3",
    fromAddress: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    toAddress: "1SuspiciousAddr99XXXXXXXXXXXX7qFbm",
    amount: 0.80,
    fee: NETWORK_FEE,
    status: "REJECTED",
    txHash: null,
    comment: "Подозрительный адрес",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-9",
    createdAt: h(6),
    updatedAt: h(5),
  },
  // 1 FAILED (timeout)
  {
    id: "tx-12",
    type: "INTERNAL",
    fromAddressId: "addr-4",
    fromAddress: "1CounterpartyXXXXXXXXXXXXXXUWLpVr",
    toAddress: "1BoatSLRHtKNngkdXEeobR76b53LETtpyT",
    amount: 0.05,
    fee: NETWORK_FEE,
    status: "FAILED",
    txHash: null,
    comment: "Микроперевод (таймаут)",
    initiatorName: "Соколова Е.А.",
    mpcSessionId: "mpc-10",
    createdAt: h(6),
    updatedAt: h(1),
  },
  // === EXTERNAL INBOUND (зачисления) ===
  {
    id: "tx-13",
    type: "EXTERNAL",
    direction: "INBOUND",
    fromAddressId: "",
    fromAddress: "3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5",
    toAddress: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    amount: 1.25,
    fee: 0,
    status: "COMPLETED",
    txHash: "d4e5f6789012345678901234def1234567890abcdef1234567890abcdef123456",
    comment: "Зачисление от контрагента",
    initiatorName: "",
    mpcSessionId: null,
    createdAt: h(8),
    updatedAt: h(8),
  },
  {
    id: "tx-14",
    type: "EXTERNAL",
    direction: "INBOUND",
    fromAddressId: "",
    fromAddress: "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
    fromAddresses: [
      "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
      "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
      "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
      "1Archive1n2C579dMsAu3iC6tWzuQJz8dN",
    ],
    toAddress: "1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw",
    amount: 3.75,
    fee: 0,
    status: "COMPLETED",
    txHash: "e5f67890123456789012345ef1234567890abcdef1234567890abcdef12345678",
    comment: "Консолидация средств от нескольких отправителей",
    initiatorName: "",
    mpcSessionId: null,
    createdAt: h(12),
    updatedAt: h(12),
  },
  {
    id: "tx-15",
    type: "EXTERNAL",
    direction: "INBOUND",
    fromAddressId: "",
    fromAddress: "1PerfectHashXXXXXXXXXXXXXXXXXXaknBJ",
    fromAddresses: [
      "1PerfectHashXXXXXXXXXXXXXXXXXXaknBJ",
      "3Kzh9qAqVWQhEsfQz7zEQL1EuSx5tyNLNS",
      "1SuspiciousAddr99XXXXXXXXXXXX7qFbm",
      "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
      "3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5",
      "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
      "1Archive1n2C579dMsAu3iC6tWzuQJz8dN",
      "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
      "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
      "1dice97ECuByXAvqXpaYzSaQuPVvrtmz6L",
      "1LovEBTCXXXXXXXXXXXXXXXXXXXYHxqR9",
    ],
    toAddress: "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    amount: 8.50,
    fee: 0,
    status: "COMPLETED",
    txHash: "f67890123456789012345678f1234567890abcdef1234567890abcdef123456789",
    comment: "Массовое зачисление",
    initiatorName: "",
    mpcSessionId: null,
    createdAt: h(24),
    updatedAt: h(24),
  },
]

export const SEED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: h(720),
    actor: "Оператор",
    action: "Создание адреса",
    entityType: "address",
    entityId: "addr-1",
    details: "Создан основной кошелёк",
  },
  {
    id: "log-2",
    timestamp: h(600),
    actor: "Оператор",
    action: "Создание адреса",
    entityType: "address",
    entityId: "addr-2",
    details: "Создан транзитный адрес 1",
  },
  {
    id: "log-3",
    timestamp: h(500),
    actor: "Оператор",
    action: "Создание адреса",
    entityType: "address",
    entityId: "addr-3",
    details: "Создан адрес хранения клиентов",
  },
  {
    id: "log-4",
    timestamp: h(48),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-1",
    details: "Черновик: 0.15 BTC → внешний адрес",
  },
  {
    id: "log-5",
    timestamp: h(6),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-11",
    details: "Перевод 0.80 BTC на подозрительный адрес",
  },
  {
    id: "log-6",
    timestamp: h(6),
    actor: "Signer 1",
    action: "Отклонение транзакции",
    entityType: "transaction",
    entityId: "tx-11",
    details: "Подозрительный адрес",
  },
  {
    id: "log-7",
    timestamp: h(5),
    actor: "Signer 2",
    action: "Отклонение транзакции",
    entityType: "transaction",
    entityId: "tx-11",
    details: "Транзакция отклонена (кворум отклонений)",
  },
  {
    id: "log-8",
    timestamp: h(4),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-10",
    details: "Перевод 0.50 BTC на архивный адрес",
  },
  {
    id: "log-9",
    timestamp: h(3),
    actor: "Signer 1",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-10",
    details: "Подпись 1/2",
  },
  {
    id: "log-10",
    timestamp: h(3),
    actor: "Signer 3",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-10",
    details: "Подпись 2/2 — транзакция исполнена",
  },
  {
    id: "log-11",
    timestamp: h(3),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-9",
    details: "Перевод 2.00 BTC из резерва",
  },
  {
    id: "log-12",
    timestamp: h(2),
    actor: "Signer 1",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-9",
    details: "Подпись 1/2",
  },
  {
    id: "log-13",
    timestamp: h(2),
    actor: "Signer 2",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-9",
    details: "Подпись 2/2 — транзакция исполнена",
  },
  {
    id: "log-14",
    timestamp: h(2),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-8",
    details: "Выплата 0.75 BTC",
  },
  {
    id: "log-15",
    timestamp: h(1),
    actor: "Signer 1",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-8",
    details: "Подпись 1/2",
  },
  {
    id: "log-16",
    timestamp: h(1),
    actor: "Signer 2",
    action: "Подтверждение транзакции",
    entityType: "transaction",
    entityId: "tx-8",
    details: "Подпись 2/2 — транзакция исполнена",
  },
  {
    id: "log-17",
    timestamp: h(1),
    actor: "Система",
    action: "Таймаут транзакции",
    entityType: "transaction",
    entityId: "tx-12",
    details: "Дедлайн истёк — транзакция провалена",
  },
  {
    id: "log-18",
    timestamp: m(5),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-7",
    details: "Консолидация 0.10 BTC",
  },
  {
    id: "log-19",
    timestamp: m(4),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-6",
    details: "Оплата услуг 0.20 BTC",
  },
  {
    id: "log-20",
    timestamp: m(3),
    actor: "Оператор",
    action: "Создание транзакции",
    entityType: "transaction",
    entityId: "tx-5",
    details: "Вывод клиента 0.30 BTC",
  },
]
